# Check for BSA Issue (AEU)

**Purpose:** Code to check if AEU has the BSA issue

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

# Initial Setup

```{r, message=FALSE, warning=FALSE}
# Import Packages ---------------------------------------------------------
library(tidyverse)
library(fuzzyjoin)
library(glue)
library(lubridate)

source('admin/global_functions/global_funcs.R')
source('programs/DWR-AEU/code/aeu_funcs.R')
source('admin/global_functions/bsa_funcs.R')
source('admin/global_functions/check_funcs.R')
```

## Read in data
```{r}
# specify the file path
data_path <- abs_pesp_path('Groups/DWR-AEU/01 Raw Data/dwr-aeu-2020.csv')

# new data to format and append
df_data <- read_quiet_csv(data_path)
```

# Clean up main taxa issues
```{r}
df_data <- df_data %>%
  distinct() %>%
  rename(Taxon = taxon)

df_data <- correct_taxon_typos(df_data)
df_data <- clean_unknowns(df_data)
df_data <- update_synonyms(df_data)

df_data <- df_data %>%
  mutate(Date = mdy(sample_date))
```

```{r}
plot_bsa_check(df_data, cell_col = 'total_cells', unit_col = 'unit_abundance')
```

```{r}
plot_bsa_check(df_data, cell_col = 'total_cells', unit_col = 'unit_abundance', x_range = c(min(df_micro$Date, na.rm = TRUE),'2014-12-31'))
```

```{r}
check_bsa_issue(df_data, cell_col = 'total_cells', unit_col = 'unit_abundance')
```

